spring:
  profiles:
    active: dev

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  #关闭thymeleaf的缓存
  thymeleaf:
    cache: false
    mode: HTML


#指定mapper文件的位置
mybatis:
  mapper-locations: classpath:mappers/*.xml



