spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    #关闭thymeleaf的缓存
    thymeleaf:
      cache: false
      mode: HTML
    #热部署
    devtools:
      restart:
        enabled: true

    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
      jackson:
        date-format: yyyy-MM-dd
        time-zone: GMT+8


#指定mapper文件的位置
mybatis:
  mapper-locations: classpath:mappers/*.xml


#日志配置
logging:
  level:
    edu:
      hut:
        keshe:
          library:
            dao: debug
    root: info
